Table <- read.tidy("elist.weighted.combined_0p15.txt")

Table$Group <- factor(Table$Group, levels=c("Baoding Cheek Healthy","Baoding Cheek Acne","Dalian Cheek Healthy","Dalian Cheek Acne" ))
Table$Domain <- factor(Table$Domain, levels=c("Intra-Bacterial","Intra-Fungal","Inter-Domain"))
Plot <- ggplot(Table, aes(x = SPIEC, colour=Domain))
Plot <- Plot + geom_density() + scale_y_continuous(expand=c(0,0),limits = c(0,10))
Plot <- Plot + facet_wrap(~Group)
Plot <- Plot + theme_classic()
Plot <- Plot + theme(axis.text.x=element_text(size=8,angle=90,vjust=0.5))
Plot <- Plot + theme(axis.line.x = element_line(color="black", size=0.5))
Plot <- Plot + theme(axis.line.y = element_line(color="black", size=0.5))
Plot <- Plot + scale_colour_manual(values=c("orange","purple","green"))
ylab <- paste0("Density (%)")
xlab <- paste0("SPIEC-EASI Correlation")
Plot <- Plot + ylab(ylab) + xlab(xlab)
Plot <- Plot + theme(legend.title = element_blank())
ggsave("density_plot_cheek.pdf",width=7,height=7,units="in")
